cygnus:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Velocity Controllers ---------------------------------------
  motor1_controller:
    type: effort_controllers/JointPositionController
    joint: Cygnus_revo_motor1
    pid: {p: 1.0, i: 0.01, d: 0.0}
  motor2_controller:
    type: effort_controllers/JointPositionController
    joint: Cygnus_revo_motor2
    pid: {p: 1.0, i: 0.01, d: 0.0}
  motor3_controller:
    type:  effort_controllers/JointPositionController
    joint: Cygnus_revo_motor3
    pid: {p: 1.0, i: 0.01, d: 0.0}
  motor4_controller:
    type:  effort_controllers/JointPositionController
    joint: Cygnus_revo_motor4
    pid: {p: 1.0, i: 0.01, d: 0.0}
